### ISSUE TITLE
Overrides break method chaining of leaflet

### ISSUE THREAD

**Issue by codeofsumit** [ProminentEdge/leaflet-measure-path#29]
Hey Per, me again :-)

Got [an issue reported](https://github.com/codeofsumit/leaflet.pm/issues/407) in leaflet.pm regarding compatibility. It's the same problem as last time, the methods here are overriding leaflet methods but do not return `this`:
https://github.com/ProminentEdge/leaflet-measure-path/blob/2e45200af8f89cf7496ebbe18e0ecaa3554bf638/leaflet-measure-path.js#L369

Hence, chaining leaflet methods like `layer.setLatLng().redraw()` throw an error. From a quick look I see the problem in all of these methods: `onRemove`, `setLatLng`, `setRadius`.

[In the leaflet source](https://github.com/Leaflet/Leaflet/blob/37d2fd15ad6518c254fae3e033177e96c48b5012/src/layer/vector/CircleMarker.js#L35), these function return the event call `fire` which is returning the instance. When overriding these function, the same instance should be returned.

Should be fixed by adding `return this` to each function. Can you quickly add that fix or should I create a PR?

Wish you all the best 👍 
Sumit

**Comment by perliedman** [comment]
Hi Sumit :wave: !

Thanks for the report, I think I fixed this now and released version 1.4.2 with the fix!

**Comment by Jumpy555** [comment]
Hi,
thank you both for your work.
I tried the last version but the problem with chaining methods still persists.

When used with the previous version of leaflet-measure-path, leaflet.pm returned this error:
TypeError: this._layer.setLatLng(...) is undefined

Now, with the last version of leaflet-measure-path, leaflet.pm returns this error:
TypeError: this._layer.setLatLng(...).redraw is not a function

Splitting the methods setLatLng and redraw in leaflet.pm resolves the problem.

**Comment by codeofsumit** [comment]
I will split it in the next release to avoid the problem. Nevertheless, chaining is a leaflet functionality that should not be broken. I’m on a phone right now so I can’t Check leaflet-measure-Path but @perliedman if you need help debugging let me know and I will have a look this weekend.

**Comment by perliedman** [comment]
Hm, let's see if I can add some tests for this to make sure it actually works as intended, I agree chaining should work.

**Comment by perliedman** [comment]
Made a pretty obvious mistake when "fixing" the problem this morning 7e554e9c331376ff0dd98552976f3ec88d46f991 :confounded: 

Will add tests when I find the time to make sure this doesn't happen again.

**Comment by codeofsumit** [comment]
@jumpy555 can you test again?

**Comment by Jumpy555** [comment]
@codeofsumit the chaining problem is still present

**Comment by RobinBressan** [comment]
@perliedman any news on this issue? A fix was done on LeafletPM to handle it, but using leaflet-measure-path with leaflet pm still gives me weird behavior on dragging, and I assume it's still linked to this issue, we might prevent PM from doing its work.

**Comment by perliedman** [comment]
Sorry, not enough time to look close at this. In general, I have very limited time for open source at the moment.

I expect this to be some minor detail, so any help from someone actually suffering from this issue would be greatly appreciated!
